plugins=(git history rsync jump)
source $ZSH/oh-my-zsh.sh
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
unsetopt HIST_SAVE_BY_COPY
unsetopt AUTO_CD
fpath+=~/.zsh-custom/comps
compinit
eval "$(starship init zsh)"
