---
- name: check installation
  stat:
    path: "{{ ansible_user_dir }}/.local/bin/poetry"
  register: poetry_installed

- name: install
  when: not poetry_installed.stat.exists
  block:
    - name: download installer
      get_url:
        url: "{{ poetry_installer_url}}"
        dest: "{{ poetry_installer_dest }}"
        force: yes
        timeout: "{{ poetry_download_timeout_sec }}"
        mode: "0755"

    - name: run installer
      shell:
        cmd: "python3 {{ poetry_installer_dest }}"

    - name: remove installer
      file:
        path: "{{ poetry_installer_dest }}"
        state: "absent"

- name: link environment configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/poetry.zsh-env"
    dest: "{{ ansible_user_dir }}/.zsh-custom/env/poetry.zsh-env"
    state: link
    force: yes

- name: export completion file
  shell: "{{ ansible_user_dir }}/.local/bin/poetry completions zsh > {{ ansible_user_dir }}/.zsh-custom/comps/_poetry"
