#!/bin/bash
name="blog.crydee.eu"
git_dir="home/git/$name.git"
checkout_dir="$(mktemp -d -t "$name-checkout-XXXXXXXXXX")"
build_dir="$(mktemp -d -t "$name-build-XXXXXXXXXX")"
web_dir="/var/www/$name"

function clean_exit {
    echo "Cleaning..."
    rm -rf "$build_dir"
    rm -rf "$checkout_dir"
    exit $1
}

trap 'clean_exit 1' ERR

while read oldrev newrev ref
do
    if [[ $ref = refs/heads/$branch ]];
    then
        echo "Cloning master in $checkout_dir..."
        git clone "$git_dir" -b master --single-branch --depth 1 "$checkout_dir"
 
        echo "Changing current directory to $checkout_dir..."
        cd "$checkout_dir"

        echo "Installing bundle..."
        bundle install

        echo "Building site in $build_dir..."
        bundle exec jekyll build -s "$checkout_dir" -d "$build_dir"

        echo "Copying the built site to $web_dir..."
        rsync -avz --delete "$build_dir/" "$web_dir"
    else
        echo "Not deploying: only the $branch branch is deployed."
    fi
done

echo "Exiting with success..."
clean_exit 0
