---
- name: link configuration
  copy:
    src: "{{ confz_files }}/{{ role_name }}/pythonrc"
    dest: "{{ ansible_user_dir }}/.pythonrc"

- name: link environment configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/python.zsh-env"
    dest: "{{ ansible_user_dir }}/.zsh-custom/env/python.zsh-env"
    state: link
    force: yes
