---
- name: install
  apt:
    name: zsh
    state: latest
  become: yes
  become_method: sudo

- name: clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- name: link configuration
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    state: link
    force: yes
  with_items:
    - zsh-custom
    - zshrc
    - zshenv

- name: change default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
  become_method: sudo
