---
- name: install git
  apt:
    name: git
    state: latest
  become: yes
  become_method: sudo

- name: link git configuration
  file:
    src: "{{ role_path }}/files/gitconfig"
    path: "{{ ansible_user_dir }}/.gitconfig"
    state: link
    force: yes

- name: link environment configuration
  file:
    src: "{{ role_path }}/files/git.zsh-env"
    path: "{{ env_dir }}/git.zsh-env"
    state: link
    force: yes
