---
- name: install
  apt:
    name: emacs
    state: latest
  become: yes
  become_method: sudo

- name: link configuration
  file:
    src: "{{ role_path }}/files/emacs.d"
    path: "{{ ansible_user_dir }}/.emacs.d"
    state: link
    force: yes

- name: link environment configuration
  file:
    src: "{{ role_path }}/files/emacs.zsh-env"
    path: "{{ env_dir }}/emacs.zsh-env"
    state: link
    force: yes
