---
- name: install git
  apt:
    name: git
    state: latest
  become: yes
  become_method: sudo

- name: download git configuration
  get_url:
    url: "https://raw.githubusercontent.com/m09/confz-files/main/git/gitconfig"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    force: yes

- name: clone confz-files
  git:
    repo: https://github.com/m09/confz-files.git
    dest: "{{ confz_files }}"
    force: yes
