---
- name: install
  apt:
    name:
      - latexmk
      - texlive
      - texlive-lang-english
      - texlive-lang-french
      - texlive-latex-extra
      - texlive-science
      - texlive-xetex
    state: latest
  become: yes
  become_method: sudo

- name: link configuration
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ ansible_user_dir }}/.{{ item }}"
    state: link
    force: yes
  with_items:
    - latexmkrc
    - indentconfig.yml
